#! /usr/bin/perl

print <<EndHtml;
<html>
<head><title>Files</title></head>
  <style type="text/css">
    margin-top: 3%; margin-right: 3%; margin-bottom: 3%; margin-left: 3%;
  </style>
<body>
<h1>Available Files</h1>
<ul>
EndHtml

foreach $elt (@ARGV)
{
    $filename = $elt;
    $filename =~s/\.pdf/\.tex/;

    local( $/, *FH ) ;
    open $file, "<" . $filename;
    $_ = <$file>;
    ($title) = /title{.*}/g;
    $title =~s/.*title{//g;
    $title =~s/}.*//g;

    $desc = "$title";
    print "<li><a href=\"$elt\">$desc</a>";
    print "\n";
}

print <<EndHtml;
</ul>
</body>
</html>
EndHtml
